---
# Setup installation 
- name: Update apt-get repo and cache
  apt:
    update_cache: yes
    cache_valid_time: 3600 

- name: Add Erlang signing key
  apt_key: 
    url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    state: present

- name: Add Erlang repository
  apt_repository: 
    repo: deb https://packages.erlang-solutions.com/ubuntu bionic contrib
    update_cache: yes
    state: present
 
- name: Add erlang version to install in /etc/apt/preferences.d/erlang file
  copy:
    dest: "/etc/apt/preferences.d/erlang"
    content: |
      Package: erlang* esl-erlang
      Pin: version 1:21.3*
      Pin-Priority: 501

- name: Install erlang and its packages
  apt:
    update_cache: True
    name: "{{ packages }}"
  vars:
    packages:
    - erlang
    - erlang-base
    - erlang-asn1
    - erlang-crypto
    - erlang-eldap
    - erlang-ftp 
    - erlang-inets
    - erlang-mnesia
    - erlang-os-mon 
    - erlang-parsetools 
    - erlang-public-key 
    - erlang-runtime-tools 
    - erlang-snmp 
    - erlang-ssl 
    - erlang-syntax-tools 
    - erlang-tftp 
    - erlang-tools 
    - erlang-xmerl
    
  
- name: Add RabbitMQ signing key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: F6609E60DC62814E

- name: Add RabbitMQ repository
  copy: 
    dest: "/etc/apt/sources.list.d/rabbitmq.list"
    content: |
      deb https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/ bionic main
      deb-src https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/ bionic main

- name: Install RabbitMQ '3.7.9' version
  apt:
    name: rabbitmq-server=3.7.9-1
    update_cache: True
  notify:
    restart rabbitmq-server  
