---
# Generate and config TLS

- name: Copy certificates
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: rabbitmq
    mode: 0644
  loop:
    - { src: "{{ ca_certificate }}", dest: "{{ certificate_dest }}" }
    - { src: "{{ server_certificate }}", dest: "{{ certificate_dest }}" }
    - { src: "{{ server_key }}", dest: "{{ certificate_dest }}" }
    - { src: "{{ combined_key }}", dest: "{{ certificate_dest }}" }

- name: Configure rabbbitmq.config and rabbitmq-env.conf files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  loop: 
    - { src: "rabbitmq.config.j2", dest: "/etc/rabbitmq/rabbitmq.config" }
    - { src: "rabbitmq-env.conf.j2", dest: "/etc/rabbitmq/rabbitmq-env.conf" }
  notify:
   restart rabbitmq-server
